### PR TITLE
Buttons scraped with newer mame.xml file

### LINKED ISSUE #420: Filter by button count not working
Referencing [Feautre Request: Filter by button count #167](https://github.com/mickelson/attract/issues/167)  and [Issue #167 - Filter by button count.  …
](https://github.com/mickelson/attract/commit/499b85cd24f4ce650cef9aff0f499d61817b18ef). I am using attract 2.3.32 and I believe this feature is not working.

Here’s some small snippets.

Emulator config:
```
import_extras        /Applications/mame0192b_macOS/catver.ini;/Applications/mame0192b_macOS/controls.ini;/Applications/mame0192b_macOS/nplayers.ini
```

romlist:
```
#Name;Title;Emulator;CloneOf;Year;Manufacturer;Category;Players;Rotation;Control;Status;DisplayCount;DisplayType;AltRomname;AltTitle;Extra;Buttons
2020bb;2020 Super Baseball (set 1);neogeo;;1991;SNK / Pallas;Sports / Baseball;2P sim;0;joystick (8-way),joystick (8-way);good;1;raster;neogeo;;;
```

I have tried generating full romlist and there is no difference. controls.ini is the latest version 0.141.1. However, the commit says „- Now parses button count from mame -listxml output and allows filtering based on buttons“ so I assume it wouldn’t even need controls.ini file.

### PR DESCRIPTION
**Pull request by keilmillerjr**
* Buttons was not scraped with the format of newer mame.xml files, and is now resolved to work with both formats
* Closes #420

Signed-off-by: Keil Miller Jr <keilmillerjr@me.com>

### CODE REVIEW

File: src/scraper_xml.cpp [hunk 1]
```diff
@@ -408,52 +408,34 @@ void FeListXMLParser::start_element(
...
 			for ( int i=0; attribute[i]; i+=2 )
 			{
 				if ( strcmp( attribute[i], "type" ) == 0 )
 					type = attribute[i+1];
 				else if ( strcmp( attribute[i], "ways" ) == 0 )
 					ways = attribute[i+1];
+				
+				if (( strcmp( attribute[i], "buttons" ) == 0 )
+						&& (*m_itr).get_info( FeRomInfo::Buttons ).empty() )
+					(*m_itr).set_info( FeRomInfo::Buttons, attribute[i+1] );
```
Comment (mickelson) [inline src/scraper_xml.cpp]: Hi, thanks for this, I am just trying to review your pull request now.  Am I correct in understanding that the three lines inserted here are what have fixed this issue (lines 426 to 428)?

Are any of the other edits in the file relevant to your fix (they don't appear to be)?

Comment (keilmillerjr) [reply src/scraper_xml.cpp]: @mickelson True. Sorry about the issues with line endings and spaces. I just realized it made this commit a mess.
